#!/usr/bin/env bash
set -e
set -u

# Menu title
title="Dotfiles menu"

# All supported choices
all=(qtile xmonad awesome leftwm bspwm sxhkd polybar alacritty ranger joshuto vim mpv zsh rofi conky dunst zathura starship)

# By default, show all (i.e., just copy the array)
show=("${all[@]}")

declare -A texts
texts[qtile]="Qtile"
texts[xmonad]="Xmonad"
texts[awesome]="Awesome"
texts[leftwm]="LeftWM"
texts[bspwm]="bspwm"
texts[sxhkd]="sxhkd"
texts[polybar]="polybar"
texts[alacritty]="Alacritty"
texts[ranger]="Ranger"
texts[joshuto]="Joshuto"
texts[vim]="Vim"
texts[mpv]="mpv"
texts[zsh]="zsh"
texts[rofi]="Rofi"
texts[conky]="Conky"
texts[dunst]="Dunst"
texts[zathura]="Zathura"
texts[starship]="Starship"

declare -A icons
icons[qtile]=""
icons[xmonad]=""
icons[awesome]=""
icons[leftwm]=""
icons[bspwm]=""
icons[sxhkd]=""
icons[polybar]=""
icons[alacritty]=""
icons[ranger]=""
icons[joshuto]=""
icons[vim]=""
icons[mpv]=""
icons[zsh]=""
icons[rofi]=""
icons[conky]=""
icons[dunst]=""
icons[zathura]=""
icons[starship]=""
icons[cancel]="×"

declare -A actions
actions[qtile]="-p ~/.config/qtile/config.py ~/.config/qtile/autostart.sh"
actions[xmonad]="-p ~/.config/xmonad/xmonad.hs ~/.config/xmobar/xmobar.hs"
actions[awesome]="~/.config/awesome/rc.lua"
actions[leftwm]="~/.config/leftwm/config.toml"
actions[bspwm]="~/.config/bspwm/bspwmrc"
actions[sxhkd]="~/.config/sxhkd/sxhkdrc"
actions[polybar]="~/.config/polybar/config -c 'set ft=toml'"
actions[alacritty]="~/.config/alacritty/alacritty.yml"
actions[ranger]="-p ~/.config/ranger/rc.conf ~/.config/ranger/scope.sh"
actions[joshuto]="-p ~/.config/joshuto/joshuto.toml ~/.config/joshuto/keymap.toml ~/.config/joshuto/mimetype.toml"
actions[vim]="-p ~/.config/nvim/init.vim ~/.config/nvim/plugins.vim ~/.config/nvim/functions.vim ~/.config/nvim/keybindings.vim"
actions[mpv]="-p ~/.config/mpv/mpv.conf ~/.config/mpv/input.conf"
actions[zsh]="-p ~/.config/zsh/.zshrc ~/.config/zsh/.zshenv"
actions[rofi]="-p ~/.config/rofi/config.rasi ~/.config/rofi/scripts/*"
actions[conky]="~/.config/conky/conky.conf -c 'set ft=lua'"
actions[dunst]="~/.config/dunst/dunstrc -c 'set ft=toml'"
actions[zathura]="~/.config/zathura/zathurarc"
actions[starship]="~/.config/starship/starship.toml"

# By default, ask for confirmation for actions that are irreversible
confirmations=()

# By default, no dry run
dryrun=false
showsymbols=true

function run {
    alacritty -e sh -c "sleep 0.5 && nvim ${actions[$entry]}" & disown
    killall rofi
}

source ~/.config/rofi/scripts/rofi-base-menu
