#!/usr/bin/env bash
set -e
set -u

# Menu title displayed on the bottom
title="Dotfiles menu"

# All supported choices
all=(qtile awesome leftwm bspwm sxhkd polybar alacritty ranger zshrc zshenv rofi dunst vim-base vim-keybindings)

# By default, show all (i.e., just copy the array)
show=("${all[@]}")

declare -A texts
texts[qtile]="Qtile"
texts[awesome]="Awesome"
texts[leftwm]="LeftWM"
texts[bspwm]="bspwm"
texts[sxhkd]="sxhkd"
texts[polybar]="polybar"
texts[alacritty]="Alacritty"
texts[ranger]="Ranger"
texts[zshrc]=".zshrc"
texts[zshenv]=".zshenv"
texts[rofi]="Rofi"
texts[dunst]="Dunst"
texts[vim-base]="Vim"
texts[vim-plugins]="Vim plugins"

declare -A icons
icons[qtile]=""
icons[awesome]=""
icons[leftwm]=""
icons[bspwm]="\uf0db"
icons[sxhkd]="\uf11c"
icons[polybar]="\uf2d1"
icons[alacritty]=""
icons[ranger]=""
icons[zshrc]=""
icons[zshenv]=""
icons[rofi]=""
icons[dunst]=""
icons[vim-base]=""
icons[vim-plugins]=""
icons[cancel]="\u01d7"

declare -A actions
actions[qtile]="~/.config/qtile/config.py"
actions[awesome]="~/.config/awesome/rc.lua"
actions[leftwm]="~/.config/leftwm/config.toml"
actions[bspwm]="~/.config/bspwm/bspwmrc"
actions[sxhkd]="~/.config/sxhkd/sxhkdrc"
actions[polybar]="~/.config/polybar/config -c 'set ft=toml'"
actions[alacritty]="~/.config/alacritty/alacritty.yml"
actions[ranger]="~/.config/ranger/rc.conf"
actions[zshrc]="~/.config/zsh/.zshrc"
actions[zshenv]="~/.config/zsh/.zshenv"
actions[rofi]="~/.config/rofi/config.rasi -c 'set ft=css'"
actions[dunst]="~/.config/dunst/dunst -c 'set ft=toml'"
actions[vim-base]="~/.config/nvim/init.vim"
actions[vim-plugins]="~/.config/nvim/plugins.vim"

# By default, ask for confirmation for actions that are irreversible
confirmations=()

# By default, no dry run
dryrun=false
showsymbols=true

function run {
    alacritty -e sh -c "sleep 0.5 && nvim ${actions[$entry]}" & disown
    killall rofi
}

source rofi-base-menu
