#!/usr/bin/env bash
set -e
set -u

# Menu title
title="Power menu"

# All supported choices
all=(shutdown reboot suspend hibernate logout lockscreen)

# By default, show all (i.e., just copy the array)
show=("${all[@]}")

declare -A texts
texts[shutdown]="Shut down"
texts[reboot]="Reboot"
texts[suspend]="Suspend"
texts[hibernate]="Hibernate"
texts[logout]="Log out"
texts[lockscreen]="Lock screen"

declare -A icons
icons[shutdown]=""
icons[reboot]=""
icons[suspend]=""
icons[hibernate]=""
icons[logout]=""
icons[lockscreen]=""
icons[cancel]="×"

declare -A actions
actions[shutdown]="systemctl poweroff"
actions[reboot]="systemctl reboot"
actions[suspend]="systemctl suspend"
actions[hibernate]="systemctl hibernate"
actions[logout]="loginctl terminate-user $USER"
actions[lockscreen]="i3lock-fancy"

# By default, ask for confirmation for actions that are irreversible
confirmations=(reboot shutdown logout)

# By default, no dry run
dryrun=false
showsymbols=true

function run {
    ${actions[$entry]}
}

source rofi-base-menu
