#!/usr/bin/env bash

# This script defines just a mode for rofi instead of being a self-contained
# executable that launches rofi by itself. This makes it more flexible than
# running rofi inside this script as now the user can call rofi as one pleases.
# For instance:
#
#   rofi -show powermenu -modi powermenu:./rofi-power-menu
#
# All credits to https://github.com/jluttine/rofi-power-menu

set -e
set -u

# All supported choices
all=(shutdown reboot suspend hibernate logout lockscreen)

# By default, show all (i.e., just copy the array)
show=("${all[@]}")

declare -A texts
texts[shutdown]="Shut down"
texts[reboot]="Reboot"
texts[suspend]="Suspend"
texts[hibernate]="Hibernate"
texts[logout]="Log out"
texts[lockscreen]="Lock screen"

declare -A icons
icons[shutdown]="\uf011"
icons[reboot]="\uf01e"
icons[suspend]="\uf186"
icons[hibernate]="\uf7c9"
icons[logout]="\uf08b"
icons[lockscreen]="\uf023"
icons[cancel]="\u00d7"

declare -A actions
actions[shutdown]="systemctl poweroff"
actions[reboot]="systemctl reboot"
actions[suspend]="systemctl suspend"
actions[hibernate]="systemctl hibernate"
actions[logout]="loginctl terminate-user $USER"
actions[lockscreen]="i3lock-fancy"

# By default, ask for confirmation for actions that are irreversible
confirmations=(reboot shutdown logout)

# By default, no dry run
dryrun=false
showsymbols=true

function run {
    ${actions[$entry]}
}

source rofi-base-menu
