#!/bin/bash
set -e
set -u

# Menu title
title="xrandr menu"

# All supported choices
all=(integrated dual-monitor external-monitor external-tv dual-tv)

# By default, show all (i.e., just copy the array)
show=("${all[@]}")

declare -A texts
texts[integrated]="Integrated display"
texts[dual-monitor]="Dual monitor (default)"
texts[external-monitor]="External monitor"
texts[external-tv]="External monitor (TV)"
texts[dual-tv]="Dual monitor (TV)"

declare -A icons
icons[integrated]=""
icons[dual-monitor]=" +"
icons[external-monitor]=""
icons[external-tv]=""
icons[dual-tv]=" +"
icons[cancel]="×"

declare -A actions
actions[integrated]="xrandr --output eDP1 --mode 1600x900 --output HDMI1 --off --output DP2-1 --off"
actions[dual-monitor]="xrandr --output eDP1 --mode 1600x900 --pos 0x180 --output DP2-1 --primary --mode 1920x1080 --pos 1600x0"
# actions[dual-monitor]="xrandr --output eDP1 --mode 1600x900 --pos 0x0 --output HDMI1 --primary --mode 1920x1080 --pos 1600x0"
actions[external-monitor]="xrandr --output DP2-1 --mode 1920x1080 --output eDP1 --off"
actions[external-tv]="xrandr --output eDP1 --off --output DP2-1 --off --output HDMI1 --mode 1360x768"
actions[dual-tv]="xrandr --output eDP1 --primary --mode 1600x900 --pos 0x0 --output HDMI1 --mode 1360x768 --pos 1600x0"

# By default, ask for confirmation for actions that are irreversible
confirmations=()

# By default, no dry run
dryrun=false
showsymbols=true

function run {
    ${actions[$entry]}
}

source ~/.config/rofi/scripts/rofi-base-menu
