#!/bin/sh

case "$1" in
    "install" | "in")
        # every directory inside ~/.config
        for i in */; do
            cp -rv $i ~/.config/
        done

        # dotfiles in the home directory
        cp .zshrc           ~
        cp .zshenv          ~
        cp .Xresources      ~
        cp .stalonetrayrc   ~

        # nvim plugin manager
        git clone --depth 1 https://github.com/wbthomason/packer.nvim \
            ~/.local/share/nvim/site/pack/packer/start/packer.nvim

        # zsh plugins
        mkdir -p ~/.config/zsh/plugins/
        git clone https://github.com/hlissner/zsh-autopair.git ~/.config/zsh/plugins/zsh-autopair
        git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.config/zsh/plugins/zsh-autosuggestions
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.config/zsh/plugins/zsh-syntax-highlighting
        ;;
    "update" | "up")
        # every directory inside ~/.config
        for i in */; do
            cp -r ~/.config/$i .
        done

        # dotfiles in the home directory
        cp ~/.zshrc         .
        cp ~/.zshenv        .
        cp ~/.Xresources    .
        cp ~/.stalonetrayrc .
        ;;
    *)
        echo "Option $1 not valid."
esac
