[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#cc0000"
idle_fg = "#000000"
info_bg = "#000000"
info_fg = "#cc0000"
good_bg = "#000000"
good_fg = "#00aa00"
warning_bg = "#000000"
warning_fg = "#ffdd00"
critical_bg = "#ffffff"
critical_fg = "#cc0000"

[icons]
name = "awesome"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 10
format = "%a %d/%m %R"
