## INSTALLATION: curl -fsSL https://starship.rs/install.sh | bash

# Don't print a new line at the start of the prompt
add_newline = false
scan_timeout = 60

# Use custom format
format = """
[┌────\ue0b6](bold cyan)$username[\ue0b0 ](fg:cyan bg:blue)$hostname[\ue0b4──────── ─ ─ ─ ](bold blue)$cmd_duration
[│](bold cyan)$directory$git_branch$git_status$rust$ruby$python$lua$java$nodejs$php$cmake
[└──](bold cyan)$character"""

[character]
success_symbol = "[❯](bold cyan)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❯](bold cyan)[❯](bold yellow)"

[directory]
truncate_to_repo = false
truncation_length = 5
truncation_symbol = "../"
style = "bold yellow"
format = "[$path]($style) [$read_only]($read_only_style)"

[cmd_duration]
style = "bold yellow"
format = "[\\[$duration\\]]($style)"

[username]
style_user = "bold fg:black bg:cyan"
format = "[$user ]($style)"
show_always = true

[hostname]
style = "bold fg:black bg:blue"
format = "[$hostname]($style)"
ssh_only = false 

[git_status]
style = "bold purple"
format = "[$all_status]($style)"
conflicted = "!!"
untracked = "?"
modified = "⏺"
staged = "➕"
deleted = "✘"
