## INSTALLATION: curl -fsSL https://starship.rs/install.sh | bash

# Don't print a new line at the start of the prompt
add_newline = true
scan_timeout = 60

# Use custom format
format = """
[┌────](bold blue)$username[](fg:white bg:blue)[](fg:cyan bg:white)$hostname[──── ─ ─](bold cyan)$cmd_duration
[│](bold blue)$directory$git_branch$git_status$rust$ruby$python$lua$java$nodejs$php$cmake
[└──](bold blue)$character"""

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"
vicmd_symbol = "[─](bold blue)"

[directory]
truncate_to_repo = false
truncation_length = 5
truncation_symbol = "../"
style = "bold purple"
format = "[$path]($style) [$read_only]($read_only_style)"

[cmd_duration]
style = "bold yellow"
format = "[ \\[$duration\\]]($style)"

[username]
style_user = "bold fg:black bg:blue"
format = "[$user ]($style)"
show_always = true

[hostname]
style = "bold fg:black bg:cyan"
format = "[ $hostname]($style)"
ssh_only = false 

[git_branch]
style = "bold red"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold red"
format = "[$all_status]($style)"
conflicted = "!"
untracked = "?"
modified = "⏺ "
staged = "➕"
deleted = "✘"
