#!/bin/sh
bspc rule -r "*"

###---Autostart---###
sxhkd &
dunst &
picom -f &
nm-applet &
flameshot &
parcellite &
blueman-applet &
xss-lock -l -- lock-script &
~/.config/polybar/launch.sh &
~/.config/scripts/battery-check.sh &
feh --bg-scale ~/.config/qtile/images/wallpaper.jpg

###---MONITORS---###
bspc monitor eDP-1 HDMI-1 -d 1 2 3 4 5 6 7 8
# bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier super
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"#242424"
bspc config active_border_color	"#24574D"
bspc config focused_border_color "#1ABC9C"
bspc config presel_feedback_color "#00FF00"
bspc config urgent_border_color "#CC0000"

###---Monitor And Desktop Settings----###
bspc config top_padding 0
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config window_gap 10
bspc config border_width 1

