[default_view]

keymap = [
    # Misc
    { keys = ["w"],             command = "show_tasks" },
    { keys = ["z"],             command = ":z " },
    { keys = ["c", "d"],        command = ":cd " },
    { keys = ["g", "h"],        command = "cd ~" },
    { keys = ["g", "d"],        command = "spawn dragon-drop -a -x %s", description = "Dragon" },
    { keys = ["ctrl+r"],        command = "reload_dirlist" },
    { keys = ["ctrl+e"],        command = "shell './%s'" },
    { keys = ["."],             command = "toggle_hidden" },
    { keys = ["="],             command = "set_mode" },
    { keys = [":"],             command = ":" },
    { keys = ["s"],             command = ":shell " },
    { keys = ["S"],             command = "spawn alacritty" },
    { keys = ["r"],             command = "open_with" },
    { keys = ["m", "d"],        command = ":mkdir " },
    { keys = ["m", "f"],        command = ":touch " },
    { keys = ["b", "b"],        command = "bulk_rename" },
    { keys = ["'"],             command = "cd_bookmark" },
    { keys = ["?"],             command = "help" },

    # Tabs
    { keys = ["g", "n"],        command = "new_tab" },
    { keys = ["g", "N"],        command = "new_tab ~" },
    { keys = ["g", "c"],        command = "close_tab" },
    { keys = ["g", "t"],        command = "tab_switch 1" },
    { keys = ["g", "T"],        command = "tab_switch -1" },
    { keys = ["\t"],            command = "tab_switch 1" },
    { keys = ["backtab"],       command = "tab_switch -1" },

    # chmod
    { keys = ["+", "r"],        command = "shell chmod +r %s",                      description = "chmod +r" },
    { keys = ["-", "r"],        command = "shell chmod -r %s",                      description = "chmod -r" },
    { keys = ["+", "w"],        command = "shell chmod +w %s",                      description = "chmod +w" },
    { keys = ["-", "w"],        command = "shell chmod -w %s",                      description = "chmod -w" },
    { keys = ["+", "x"],        commands = ["shell chmod +x %s", "reload_dirlist"], description = "chmod +x" },
    { keys = ["-", "x"],        commands = ["shell chmod -x %s", "reload_dirlist"], description = "chmod -x" },

    # arrow keys
    { keys = ["arrow_up"],      command = "cursor_move_up" },
    { keys = ["arrow_down"],    command = "cursor_move_down" },
    { keys = ["arrow_left"],    command = "cd .." },
    { keys = ["arrow_right"],   command = "open" },
    { keys = ["\n"],            command = "open" },
    { keys = ["end"],           command = "cursor_move_end" },
    { keys = ["home"],          command = "cursor_move_home" },
    { keys = ["page_up"],       command = "cursor_move_page_up" },
    { keys = ["page_down"],     command = "cursor_move_page_down" },
    { keys = ["ctrl+u"],        command = "cursor_move_page_up 0.5" },
    { keys = ["ctrl+d"],        command = "cursor_move_page_down 0.5" },

    # vim-like keybindings
    { keys = ["h"],             command = "cd .." },
    { keys = ["l"],             command = "open" },
    { keys = ["j"],             command = "cursor_move_down" },
    { keys = ["k"],             command = "cursor_move_up" },
    { keys = ["J"],             command = "cursor_move_page_down 0.5" },
    { keys = ["K"],             command = "cursor_move_page_up 0.5" },
    { keys = ["g", "g"],        command = "cursor_move_home" },
    { keys = ["G"],             command = "cursor_move_end" },

    # History
    { keys = ["H"],             command = "history_prev" },
    { keys = ["L"],             command = "history_next" },

    { keys = ["["],             command = "parent_cursor_move_up" },
    { keys = ["]"],             command = "parent_cursor_move_down" },

    # Copy/paste
    { keys = ["y", "."],        command = "copy_filename_without_extension" },
    { keys = ["y", "n"],        command = "copy_filename" },
    { keys = ["y", "p"],        command = "copy_filepath" },
    { keys = ["y", "d"],        command = "copy_dirpath" },
    { keys = ["y", "l"],        command = "symlink_files --relative=true" },
    { keys = ["y", "L"],        command = "symlink_files" },
    { keys = ["y", "y"],        command = "copy_files" },
    { keys = ["d", "d"],        command = "cut_files" },
    { keys = ["d", "D"],        command = "delete_files --noconfirm" },
    # { keys = ["d", "D"],        commands = ["delete_thumbnail", "delete_files --noconfirm"], description = "trash_files" },
    # { keys = ["d", "T"],        command = "delete_thumbnail", description = "delete_thumbnail" },
    { keys = ["d", "T"],        command = "spawn /home/azad/.config/joshuto/scripts/delete_thumbnail %p", description = "delete_thumbnail" },
    { keys = ["p", "p"],        command = "paste_files --skip_exist=true" },
    { keys = ["p", "P"],        command = "paste_files --overwrite=true" },

    # Rename
    { keys = ["a"],             command = "rename_append_base" },
    { keys = ["A"],             command = "rename_append" },
    { keys = ["I"],             command = "rename_prepend" },
    { keys = ["c", "w"],        command = "rename_keep_ext" },
    { keys = ["c", "W"],        command = ":rename " },

    # Select
    { keys = [" "],             command = "select --toggle=true" },
    { keys = ["backspace"],     commands = ["cursor_move_up", "select --deselect=true", "cursor_move_up"] },
    { keys = ["v"],             command = "select --all=true --toggle=true" },
    { keys = ["u", "v"],        command = "select --all=true --deselect=true" },
    { keys = ["V"],             command = "toggle_visual" },

    # Search
    { keys = ["/"],             command = ":search_inc " },
    { keys = ["|"],             command = ":search " },
    { keys = ["\\"],            command = ":search_glob " },
    { keys = ["f"],             command = "search_fzf" },
    { keys = ["F"],             command = "subdir_fzf" },
    { keys = ["n"],             command = "search_next" },
    { keys = ["N"],             command = "search_prev" },

    # Sort
    { keys = ["o", "r"],        command = "sort reverse" },
    { keys = ["o", "l"],        command = "sort lexical" },
    { keys = ["o", "m"],        command = "sort mtime --reverse=true" },
    { keys = ["o", "n"],        command = "sort natural --reverse=false" },
    { keys = ["o", "s"],        command = "sort size" },
    { keys = ["o", "e"],        command = "sort ext" },

    # Numbered commands
    { keys = ["1"],             command = "numbered_command 1" },
    { keys = ["2"],             command = "numbered_command 2" },
    { keys = ["3"],             command = "numbered_command 3" },
    { keys = ["4"],             command = "numbered_command 4" },
    { keys = ["5"],             command = "numbered_command 5" },
    { keys = ["6"],             command = "numbered_command 6" },
    { keys = ["7"],             command = "numbered_command 7" },
    { keys = ["8"],             command = "numbered_command 8" },
    { keys = ["9"],             command = "numbered_command 9" },
]

[task_view]
keymap = [
    { keys = ["q"],             command = "show_tasks" },
    { keys = ["j"],             command = "cursor_move_down" },
    { keys = ["k"],             command = "cursor_move_up" },
    { keys = ["J"],             command = "cursor_move_page_down 0.5" },
    { keys = ["K"],             command = "cursor_move_page_up 0.5" },
    { keys = ["g", "g"],        command = "cursor_move_home" },
    { keys = ["G"],             command = "cursor_move_end" },
]

[help_view]
keymap = [
    { keys = ["q"],             command = "help" },
    { keys = ["j"],             command = "cursor_move_down" },
    { keys = ["k"],             command = "cursor_move_up" },
    { keys = ["J"],             command = "cursor_move_page_down 0.5" },
    { keys = ["K"],             command = "cursor_move_page_up 0.5" },
    { keys = ["g", "g"],        command = "cursor_move_home" },
    { keys = ["G"],             command = "cursor_move_end" },
]
