# case_insensitive_ext = true

[tabs.active]
invert = true
bold = true

[selection]
fg = "light_yellow"
bold = true
prefix = " "

[regular]
fg = "light_white"

[executable]
fg = "light_green"

[directory]
fg = "blue"
bold = true

[link]
fg = "cyan"
bold = true

[link_invalid]
fg = "red"
bold = true

[socket]
fg = "light_magenta"
bold = true

[visual_mode_selection]
bg = "black"
fg = "light_yellow"
bold = true
prefix = "  "

[ext]

# images
bmp.fg  = "yellow"
gif.fg  = "yellow"
ico.fg  = "yellow"
jpeg.fg = "yellow"
jpg.fg  = "yellow"
png.fg  = "yellow"
ppm.fg  = "yellow"
svg.fg  = "yellow"
webp.fg = "yellow"

# audio/videos
3gp.fg  = "magenta"
avi.fg  = "magenta"
flac.fg = "magenta"
m3u.fg  = "magenta"
m4a.fg  = "magenta"
m4v.fg  = "magenta"
mid.fg  = "magenta"
mkv.fg  = "magenta"
mp3.fg  = "magenta"
mp4.fg  = "magenta"
mov.fg  = "magenta"
ogg.fg  = "magenta"
ts.fg   = "magenta"
wav.fg  = "magenta"
webm.fg = "magenta"
wmv.fg  = "magenta"

# archives
7z.fg   = "red"
apk.fg  = "red"
bz2.fg  = "red"
deb.fg  = "red"
gz.fg   = "red"
jar.fg  = "red"
rar.fg  = "red"
rpm.fg  = "red"
tar.fg  = "red"
tgz.fg  = "red"
xz.fg   = "red"
xopp.fg = "red"
zip.fg  = "red"
zst.fg  = "red"
