local c = {
	fg      = "#F8F8F2",
	fg_alt1 = "#cfcfc1",
	fg_alt2 = "#7E8E91",

	bg      = "#272822",
	bg_alt1 = "#3E3D32",
	bg_alt2 = "#75715E",

	black   = "#000000",
	grey    = "#465457",
	orange  = "#FD971F",
	yellow  = "#E6DB74",
	green   = "#A6E22E",
	cyan    = "#66D9EF",
	magenta = "#F92672",
	purple  = "#AE81FF",

	blue    = "#5294E2",
	red     = "#FF0000",
}

local syntax = {
    Normal          = { fg = c.fg                                           },
    SignColumn      = { fg = c.fg,      bg = c.bg                           },
    FoldColumn      = { fg = c.grey,    bg = c.black                        },
    VertSplit       = { fg = c.black,   bg = c.bg                           },
    Folded          = { fg = c.blue,    bg = c.bg                           },
    EndOfBuffer     = { fg = c.bg                                           },
    Search          = { fg = c.fg,      bg = c.bg_alt2                      },
    IncSearch       = { fg = c.black,   bg = c.yellow                       },
    ColorColumn     = {                 bg = c.bg                           },
    CursorColumn    = { bg = c.bg_alt1                                      },
    CursorLine      = { bg = c.bg_alt1                                      },
    CursorLineNr    = { fg = c.orange,                  bold = true         },
    LineNr          = { fg = c.fg_alt2, bg = c.bg                           },
    DiffAdd         = { fg = c.blue,    bg = c.bg                           },
    DiffChange      = { fg = c.fg,      bg = c.bg                           },
    DiffDelete      = { fg = c.red,     bg = c.bg                           },
    DiffText        = { fg = c.black,   bg = c.fg                           },
    Directory       = { fg = c.cyan,                    bold = true         },
    ErrorMsg        = { fg = c.red,                     bold = true         },
    WarningMsg      = { fg = c.fg,                      bold = true         },
    ModeMsg         = { fg = c.fg,                      bold = true         },
    MatchParen      = { fg = c.orange,  bg = c.black                        },
    Whitespace      = { fg = c.grey                                         },
    Pmenu           = { fg = c.fg,      bg = c.bg                           },
    PmenuSel        = { fg = c.bg,      bg = c.blue                         },
    PmenuSelBold    = { fg = c.bg,      bg = c.blue                         },
    PmenuSbar       = {                 bg = c.grey                         },
    PmenuThumb      = { fg = c.purple,  bg = c.fg_alt1                      },
    Question        = { fg = c.yellow                                       },
    NormalFloat     = { fg = c.fg_alt1, bg = c.bg                           },
    Tabline         = { fg = c.fg,      bg = c.grey                         },
    TabLineSel      = { fg = c.bg,      bg = c.yellow,  bold = true         },
    TabLineFill     = {                 bg = c.grey                         },
    SpellBad        = { fg = c.red,                     undercurl = true    },
    SpellCap        = { fg = c.blue,                    undercurl = true    },
    SpellLocal      = { fg = c.cyan,                    undercurl = true    },
    SpellRare       = { fg = c.purple,                  undercurl = true    },
    Visual          = {                 bg = c.bg_alt1                      },
    VisualNOS       = { fg = c.black,   bg = c.bg_alt1                      },
    Debug           = { fg = c.bg_alt2,                 bold = true         },
	Boolean         = { fg = c.purple                                       },
    Number          = { fg = c.purple                                       },
    Float           = { fg = c.purple                                       },
    PreProc         = { fg = c.orange                                       },
    PreCondit       = { fg = c.orange                                       },
    Include         = { fg = c.orange                                       },
    Define          = { fg = c.orange                                       },
    Conditional     = { fg = c.magenta,                 bold = true         },
    Repeat          = { fg = c.magenta,                 bold = true         },
    Keyword         = { fg = c.magenta,                 bold = true         },
    Typedef         = { fg = c.magenta                                      },
    Exception       = { fg = c.orange,                  bold = true         },
    Statement       = { fg = c.magenta,                 bold = true         },
    Error           = { fg = c.red                                          },
    StorageClass    = { fg = c.orange                                       },
    Tag             = { fg = c.magenta,                 bold = true         },
    Label           = { fg = c.magenta                                      },
    Structure       = { fg = c.orange                                       },
    Operator        = { fg = c.magenta                                      },
    Title           = { fg = c.orange,                  bold = true         },
    Special         = { fg = c.cyan,                    italic = true       },
    SpecialChar     = { fg = c.cyan,                    italic = true       },
    SpecialKey      = { fg = c.cyan,                    italic = true       },
    Type            = { fg = c.cyan                                         },
    Function        = { fg = c.green                                        },
    String          = { fg = c.yellow                                       },
    Character       = { fg = c.green                                        },
    Constant        = { fg = c.purple,                  bold = true         },
    Macro           = { fg = c.green,                   italic = true       },
    Identifier      = { fg = c.orange                                       },
    Comment         = { fg = c.fg_alt2                                      },
    SpecialComment  = { fg = c.bg_alt1                                      },
    Todo            = { fg = c.purple                                       },
    Delimiter       = { fg = c.fg_alt2                                      },
    Conceal         = { fg = c.bg_alt2                                      },
    Ignore          = { fg = c.bg_alt2                                      },

    -- IndentBlankLine
    IndentBlankLineChar = { fg = c.grey     },

	-- nvim-cmp
    CmpItemAbbr         = { fg = c.fg       },
    CmpItemAbbrMatch    = { fg = c.blue     },
    CmpItemMenu         = { fg = c.fg       },
    CmpItemKindVariable = { fg = c.fg       },
    CmpItemKindEnum     = { fg = c.cyan     },
    CmpItemKindClass    = { fg = c.cyan     },
    CmpItemKindMethod   = { fg = c.green    },
    CmpItemKindFunction = { fg = c.green    },
    CmpItemKindKeyWord  = { fg = c.magenta  },
    CmpItemKindField    = { fg = c.orange   },
    CmpItemKindModule   = { fg = c.orange   },
    CmpItemKindProperty = { fg = c.orange   },
    CmpItemKindConstant = { fg = c.purple   },
    CmpItemKindSnippet  = { fg = c.purple   },
    CmpItemKindFile     = { fg = c.magenta  },
    CmpItemKindFolder   = { fg = c.cyan     },
    CmpItemKindText     = { fg = c.fg_alt2  },

    -- Telescope
    TelescopeTitle          = { fg = c.magenta,                 bold = true },
    TelescopeBorder         = { fg = c.yellow                               },
    TelescopePromptBorder   = { fg = c.cyan                                 },
    TelescopePromptCounter  = { fg = c.purple,                  bold = true },
    TelescopeMatching       = { fg = c.cyan                                 },
    TelescopeSelection      = {                 bg = c.bg_alt1, bold = true },
    TelescopeSelectionCaret = { fg = c.yellow                               },
    TelescopeMultiSelection = { fg = c.blue                                 },

    -- Treesitter
    ["@variable"]           = { link = "Normal"     },
    ["@constructor"]        = { link = "Type"       },
    ["@constructor.lua"]    = { link = "Delimiter"  },
}

for group, conf in pairs(syntax) do
    vim.api.nvim_set_hl(0, group, conf)
end
