#!/bin/bash

case "$1" in
    m)
        mode="modified"
        regex="^ M"
        col=3
        ;;
    n)
        mode="new"
        regex="^\?\?"
        col=2
        ;;
    c)
        mode="conflicting"
        regex="^UU"
        col=2
        ;;
    *)
        echo "Unexpected argument: $1"
        exit 1
esac

files="$(git status -s "${2:-.}" | grep -E "$regex" | cut -d " " -f "$col")"

if [[ -n "$files" ]]; then
    # shellcheck disable=2086
    nvim -p $files
else
    echo "No $mode files found."
    exit 1
fi
