#!/bin/bash
# Edit modified, new, conflicting (or a combination of the tree) in nvim

function update_regex {
    [ -n "$regex" ] && regex+='|'
    regex="${regex}$1"
}

while getopts 'mnc' flag; do
    case "$flag" in
        m)  # modified
            update_regex ' M'
            ;;
        n)  # new
            update_regex '\?\?'
            ;;
        c)  # conflicting
            update_regex 'UU'
            ;;
        *)
            echo "Unexpected flag: $1" >&2
            exit 1
            ;;
    esac
done

shift $((OPTIND - 1))
files="$(git status -s "${2:-.}" | grep -E "^($regex) " | awk '{ print $NF }')"

if [[ -n "$files" ]]; then
    # shellcheck disable=2086
    nvim -p $files
else
    echo 'No matching files found.'
    exit 1
fi
