#!/bin/bash
# Shuffle play all videos in the current directory (recursively)
# or from path specified as first argument

dir="$(pwd)"

if [ -d "$1" ]; then
    dir="$1"
    shift 1
elif [ -n "$1" ]; then
    pattern="$1.*"
    shift 1
fi

fd -0 -i "$pattern\.(m4v|mp4|mov|avi)$" "$dir" | xargs -0 mpv --shuffle "$@"
