modkey = "Mod4"
workspaces = []
tags = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]

layouts = [
    "MainAndVertStack", 
    "MainAndHorizontalStack", 
    "EvenVertical", 
    "EvenHorizontal", 
    "Fibonacci", 
    "Monocle"
]

[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "Execute"
value = "alacritty -t Ranger -e ranger"
modifier = ["modkey"]
key = "e"

[[keybind]]
command = "Execute"
value = "rofi -modi drun,run -show drun"
modifier = ["modkey"]
key = "space"

[[keybind]]
command = "Execute"
value = "rofi -modi menu:rofi-power-menu -show menu"
modifier = ["modkey", "Shift"]
key = "e"

[[keybind]]
command = "Execute"
value = "rofi -modi menu:rofi-xrandr-menu -show menu"
modifier = ["modkey", "Shift"]
key = "x"

[[keybind]]
command = "Execute"
value = "rofi -modi menu:rofi-dotfiles-menu -show menu"
modifier = ["modkey", "Shift"]
key = "d"

[[keybind]]
command = "Execute"
value = "firefox"
modifier = ["modkey"]
key = "f"

[[keybind]]
command = "Execute"
value = "flameshot gui"
modifier = ["modkey"]
key = "s"

[[keybind]]
command = "Execute"
value = "pactl set-sink-volume @DEFAULT_SINK@ +5%"
modifier = ["modkey"]
key = "up"

[[keybind]]
command = "Execute"
value = "pactl set-sink-volume @DEFAULT_SINK@ -5%"
modifier = ["modkey"]
key = "down"

[[keybind]]
command = "Execute"
value = "pactl set-sink-mute @DEFAULT_SINK@ toggle"
modifier = ["modkey"]
key = "m"

[[keybind]]
command = "Execute"
value = "deadbeef --play-pause"
modifier = ["modkey"]
key = "p"

[[keybind]]
command = "CloseWindow"
modifier = ["modkey", "Shift"]
key = "q"

[[keybind]]
command = "SoftReload"
modifier = ["modkey", "Shift"]
key = "r"

[[keybind]]
command = "FloatingToTile"
modifier = ["modkey", "Shift"]
key = "f"

[[keybind]]
command = "MoveToLastWorkspace"
modifier = ["modkey", "Shift"]
key = "w"

[[keybind]]
command = "FocusWindowUp"
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusWindowDown"
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "MoveWindowUp"
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "MoveWindowTop"
modifier = ["modkey"]
key = "o"

[[keybind]]
command = "NextLayout"
modifier = ["modkey"]
key = "Tab"

[[keybind]]
command = "PreviousLayout"
modifier = ["modkey", "Shift"]
key = "Tab"

[[keybind]]
command = "FocusWorkspaceNext"
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "FocusWorkspacePrevious"
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "9"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "5"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "6"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "7"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "8"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Shift"]
key = "9"
