#!/usr/bin/env bash
set -e
set -u

# Menu title
title="Dotfiles menu"

# All supported choices
all=(autostart qtile xmonad awesome leftwm bspwm sxhkd polybar alacritty ranger joshuto nvim mpv zsh rofi conky dunst picom zathura starship)

# By default, show all (i.e., just copy the array)
show=("${all[@]}")

declare -A texts
texts[autostart]="Autostart"
texts[qtile]="Qtile"
texts[xmonad]="Xmonad"
texts[awesome]="Awesome"
texts[leftwm]="LeftWM"
texts[bspwm]="bspwm"
texts[sxhkd]="sxhkd"
texts[polybar]="polybar"
texts[alacritty]="Alacritty"
texts[ranger]="Ranger"
texts[joshuto]="Joshuto"
texts[nvim]="NeoVim"
texts[mpv]="mpv"
texts[zsh]="zsh"
texts[rofi]="Rofi"
texts[conky]="Conky"
texts[dunst]="Dunst"
texts[picom]="Picom"
texts[zathura]="Zathura"
texts[starship]="Starship"

declare -A icons
icons[autostart]=""
icons[qtile]=""
icons[xmonad]=""
icons[awesome]=""
icons[leftwm]=""
icons[bspwm]=""
icons[sxhkd]=""
icons[polybar]=""
icons[alacritty]=""
icons[ranger]=""
icons[joshuto]=""
icons[nvim]=""
icons[mpv]=""
icons[zsh]=""
icons[rofi]=""
icons[conky]=""
icons[dunst]=""
icons[picom]=""
icons[zathura]=""
icons[starship]=""
icons[cancel]="×"

declare -A actions
actions[autostart]="-p ~/git-repos/dotfiles/autostart.csv"
actions[qtile]="-p $XDG_CONFIG_HOME/qtile/config.py"
actions[xmonad]="-p $XDG_CONFIG_HOME/xmonad/xmonad.hs $XDG_CONFIG_HOME/xmobar/xmobar.hs"
actions[awesome]="$XDG_CONFIG_HOME/awesome/rc.lua"
actions[leftwm]="$XDG_CONFIG_HOME/leftwm/config.toml"
actions[bspwm]="$XDG_CONFIG_HOME/bspwm/bspwmrc"
actions[sxhkd]="$XDG_CONFIG_HOME/sxhkd/sxhkdrc"
actions[polybar]="$XDG_CONFIG_HOME/polybar/config.ini"
actions[alacritty]="-p $XDG_CONFIG_HOME/alacritty/alacritty.yml $XDG_CONFIG_HOME/alacritty/colorscheme.yml $XDG_CONFIG_HOME/alacritty/keybindings.yml"
actions[ranger]="-p $XDG_CONFIG_HOME/ranger/rc.conf $XDG_CONFIG_HOME/ranger/scope.sh"
actions[joshuto]="-p $XDG_CONFIG_HOME/joshuto/joshuto.toml $XDG_CONFIG_HOME/joshuto/keymap.toml $XDG_CONFIG_HOME/joshuto/mimetype.toml"
actions[nvim]="-p $XDG_CONFIG_HOME/nvim/init.lua $XDG_CONFIG_HOME/nvim/lua/options.lua $XDG_CONFIG_HOME/nvim/lua/plugins.lua $XDG_CONFIG_HOME/nvim/lua/functions.lua $XDG_CONFIG_HOME/nvim/lua/autocmds.lua $XDG_CONFIG_HOME/nvim/lua/keymaps.lua"
actions[mpv]="-p $XDG_CONFIG_HOME/mpv/mpv.conf $XDG_CONFIG_HOME/mpv/input.conf"
actions[zsh]="-p $XDG_CONFIG_HOME/zsh/.zshrc $XDG_CONFIG_HOME/zsh/.zshenv"
actions[rofi]="-p $XDG_CONFIG_HOME/rofi/config.rasi $XDG_CONFIG_HOME/rofi/scripts/*"
actions[conky]="$XDG_CONFIG_HOME/conky/conky.conf -c 'set ft=lua'"
actions[dunst]="$XDG_CONFIG_HOME/dunst/dunstrc -c 'set ft=toml'"
actions[picom]="$XDG_CONFIG_HOME/picom/picom.conf"
actions[zathura]="$XDG_CONFIG_HOME/zathura/zathurarc"
actions[starship]="$XDG_CONFIG_HOME/starship/starship.toml"

# By default, ask for confirmation for actions that are irreversible
confirmations=()

# By default, no dry run
dryrun=false
showsymbols=true

function run {
    alacritty -e sh -c "sleep 0.5 && nvim ${actions[$entry]}" & disown
    killall rofi
}

source "$XDG_CONFIG_HOME/rofi/scripts/rofi-base-menu"
